/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JOptionPane;
import model.Casa;
import model.Departamento;
import model.Inmobiliaria;
import model.Propiedad;

/**
 *
 * @author mnava
 */
public class VentanaAltaPropiedad extends javax.swing.JFrame {
	private Inmobiliaria inmobiliaria;

	/**
	 * Creates new form VentanaAltaPropiedad
	 */
	public VentanaAltaPropiedad() {
		initComponents();
	}
	
	public VentanaAltaPropiedad(Inmobiliaria inmobiliaria) {
		initComponents();

		this.inmobiliaria = inmobiliaria;

		lblPrecioExpensas.setVisible(false);
		txtPrecioExpensas.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spnCantHabitaciones = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioBaseAlquiler = new javax.swing.JTextField();
        chkUsoComercial = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        spnCantInquilinos = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        radCasa = new javax.swing.JRadioButton();
        radDepartamento = new javax.swing.JRadioButton();
        chkPoseeGarage = new javax.swing.JCheckBox();
        lblPrecioExpensas = new javax.swing.JLabel();
        txtPrecioExpensas = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Dirección");

        jLabel2.setText("Cantidad de Habitaciones");

        jLabel3.setText("Precio base de alquiler");

        chkUsoComercial.setText("Uso comercial");

        jLabel4.setText("Cantidad de Inquilinos");

        jLabel5.setText("Tipo de propiedad");

        buttonGroup1.add(radCasa);
        radCasa.setSelected(true);
        radCasa.setText("Casa");
        radCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCasaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radDepartamento);
        radDepartamento.setText("Departamento");
        radDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDepartamentoActionPerformed(evt);
            }
        });

        chkPoseeGarage.setText("Posee garage");

        lblPrecioExpensas.setText("Precio de las expensas");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion)
                    .addComponent(txtPrecioBaseAlquiler)
                    .addComponent(txtPrecioExpensas)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPoseeGarage)
                            .addComponent(radDepartamento)
                            .addComponent(radCasa)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(spnCantHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(chkUsoComercial)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(lblPrecioExpensas)
                            .addComponent(spnCantInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 503, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnCantHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecioBaseAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(chkUsoComercial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnCantInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(radCasa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radDepartamento)
                .addGap(18, 18, 18)
                .addComponent(chkPoseeGarage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecioExpensas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecioExpensas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

		//Alta de la propiedad
		Propiedad p = null;

		//validacion
		if (txtDireccion.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "La direccion no debe ser vacia");
			return;
		}

		String direccion = txtDireccion.getText();
		int cantHabitaciones = (int) spnCantHabitaciones.getValue();
		double precioBaseAlquiler = Double.parseDouble(txtPrecioBaseAlquiler.getText());
		boolean esUsoComercial = chkUsoComercial.isSelected();
		int cantInquilinos = (int) spnCantInquilinos.getValue();

		if (radCasa.isSelected()) {

		    boolean poseeGaraje = chkPoseeGarage.isSelected();
			p = new Casa(direccion, cantHabitaciones, precioBaseAlquiler, esUsoComercial, cantInquilinos, poseeGaraje);

		} else {

			double precioExpensas = Double.parseDouble(txtPrecioExpensas.getText());
			p = new Departamento(direccion, cantHabitaciones, precioBaseAlquiler, esUsoComercial, cantInquilinos, precioExpensas);
		}

		inmobiliaria.agregarPropiedad(p);
		this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void radCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCasaActionPerformed
		chkPoseeGarage.setVisible(true);

		lblPrecioExpensas.setVisible(false);
		txtPrecioExpensas.setVisible(false);
    }//GEN-LAST:event_radCasaActionPerformed

    private void radDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDepartamentoActionPerformed
		chkPoseeGarage.setVisible(false);

		lblPrecioExpensas.setVisible(true);
		txtPrecioExpensas.setVisible(true);

    }//GEN-LAST:event_radDepartamentoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VentanaAltaPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VentanaAltaPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VentanaAltaPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VentanaAltaPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new VentanaAltaPropiedad().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkPoseeGarage;
    private javax.swing.JCheckBox chkUsoComercial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblPrecioExpensas;
    private javax.swing.JRadioButton radCasa;
    private javax.swing.JRadioButton radDepartamento;
    private javax.swing.JSpinner spnCantHabitaciones;
    private javax.swing.JSpinner spnCantInquilinos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtPrecioBaseAlquiler;
    private javax.swing.JTextField txtPrecioExpensas;
    // End of variables declaration//GEN-END:variables
}
